### ISSUE TITLE
feat: support a way to modify fetcher default options on the fly

### ISSUE THREAD

**Issue by fy0** [unjs/ofetch#201] opened 2022-12-24 12:32 UTC
### Describe the feature

Like this:
```js
export let apiFetch = ofetch.create({
  baseURL: urlBase,
  retry: 3,
  method: 'POST'
})
```

```js
async function signin() {
    // ... sign in
   apiFetch.defaults.headers['token'] = userToken
}
```

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by yesworld** [comment] 2022-12-26 12:33
I have the same question!

**Comment by NozomuIkuta** [comment] 2023-01-12 07:09
As far as I see the code, currently created fetcher functions don't have a reference to the object of default options passed when they are created.

Workaround at the moment would be to keep functions themselves immutable and implement a wrapper fetcher factory function whose returned value is to be assigned to a reusable variable (e.g. `apiFetch` in your code).

```typescript
// Not tested, just for inspiration

export let apiFetch = createFetcher()

export function createFetcher (options = {}) {
  return ofetch.create({
    baseURL: urlBase,
    retry: 3,
    method: 'POST',
    ...options
  })
}

// later...

apiFetch = createFetcher({ 
  headers: { 
    token: userToken
  }
})
```

**Comment by pi0** [comment] 2023-08-23 11:56
Hi and thanks for opening this issue. It is by design that ofetch does not supports modifiable defaults assignined to instance to avoid unpredictable behavior. You can always make a wrapper function that provides dynamic config.

**Closed by pi0** 2023-08-23 11:56 UTC
Labels: enhancement
