### ISSUE TITLE
[question]: How to access to meta requestStartedAt

### ISSUE THREAD

**Issue by joffreyBerrier** [unjs/ofetch#125] opened 2022-09-15 13:38 UTC
I have create a log request for axios and I wouldlike to use it on ohmyfetch
```javascript
const logRequest = request => {
  const date = new Date()
  const dateTime = `${date.getDate()}.${date.getMonth() +
    1}.${date.getFullYear()} ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}`
  const grey = '\x1b[90m'
  const pink = '\x1b[35m'
  const green = '\x1b[32m'

  // format 27.1.2021 19:7:49 200 api/v1/..  (..ms)
  const message = request => {
    const date = `${grey} ${dateTime}`
    const status = `${green} ${request?.response?.status || request.status}`
    const url = `${grey} ${request.config.baseURL}${request.config.url}`
    const responseTime = `${pink} (${new Date().getTime() -
      request.config.meta.requestStartedAt}ms)`

    return `${date} ${status} ${url} ${responseTime}`
  }

  console.log(message(request))
}
```

But I can't see `meta` or `requestStartedAt` on the Interceptors `onResponse` 

Do you have an idea ?

**Comment by NozomuIkuta** [comment] 2023-01-11 22:35
As far as I googled, `requestStartedAt` is not a standard API, but just a meta that you or someone else added to `request.config.meta`.

This issue is potentially duplicate of #103 in that goals of those are to extend the `context`.
So, let me close this issue and please watch #103 as single source of truth.

**Closed by NozomuIkuta** 2023-01-11 22:35 UTC
Labels: duplicate
