### ISSUE TITLE
How to remove 'text/plain;charset=UTF-8' from content-type header?

### ISSUE THREAD

**Issue by ian4uia** [unjs/ofetch#88] opened 2022-06-10 10:02 UTC
Hi, I am trying to send a post request to PostgREST to invoke a stored procedure:
```
  const data = await $fetch('http://http-logger:3001/rpc/test_proc', {
    method: 'post',
    headers: {
      Prefer: 'params=single-object',
      Accept: 'application/json',
      'Content-Type':  'application/json'
    },
    body: {some: 'json'}
})
```
Results in this request:
```
POST /rpc/test_proc HTTP/1.1
host: http-logger:3001
connection: keep-alive
prefer: params=single-object
accept: application/json
content-type: application/json, text/plain;charset=UTF-8
accept-language: *
sec-fetch-mode: cors
user-agent: undici
accept-encoding: gzip, deflate
content-length: 15


{"some":"json"}
```
I need to remove the 'text/plain;charset=UTF-8' part from the content-type.  Is this possible?  Should it even be there as I have explicitly defined the content-type header?
Many thanks
Ian

**Comment by mvdschee** [comment] 2022-06-23 05:14
@ian4uia You have made a typo, headers are case sensitive, you can overwrite `content-type` with lowercase instead of capitalised `Content-Type`

**Comment by phorcys420** [comment] 2022-08-02 07:44
> You have made a typo, headers are case sensitive, you can overwrite ``content-type`` with lowercase instead of capitalised ``Content-Type``
it's not a typo, it's supposed to work too

**Comment by mvdschee** [comment] 2022-08-02 08:18
Could that it's always adding the `text/plain;charset=UTF-8` on any content-type which would be not very helpful.


 But what I saw in [fetch.js #L121](https://github.com/unjs/ohmyfetch/blob/main/src/fetch.ts#L121) if you wanted to overwrite it you needs to use `content-type` instead of `Content-Type`

**Comment by phorcys420** [comment] 2022-08-02 08:19
I'm pretty sure that works for ohmyfetch, but it's probably an issue with the underlying fetch libraries used (for my case, it's using undici.fetch)

**Comment by phorcys420** [comment] 2022-08-03 07:08
I can confirm that this is only an issue with undici fetch (``globalThis.fetch``)

**Comment by phorcys420** [comment] 2022-08-03 07:19
Actually, it is only an issue with undici fetch in ohmyfetch context, here's a snippet to test it out :

```js

```js
import http from "node:http";

import { $fetch } from "ohmyfetch/node";

const server = http.createServer((req, res) => {
	console.log(req.headers);

  res.end();
});

server.listen(8000);

for(const fetchImpl of [fetch, $fetch]) {
	await fetchImpl("http://localhost:8000", {
		body: { lo: "dibidon" },

		headers: {
			"content-type": "application/json"
		},

		method: "POST"
	});
}
```

globalThis.fetch:

```json
{
  host: 'localhost:8000',
  connection: 'keep-alive',
  'content-type': 'application/json',
  accept: '*/*',
  'accept-language': '*',
  'sec-fetch-mode': 'cors',
  'user-agent': 'undici',
  'accept-encoding': 'gzip, deflate',
  'content-length': '0'
}
```

ohmyfetch:
```json
{
  host: 'localhost:8000',
  connection: 'keep-alive',
  'content-type': 'application/json',
  accept: '*/*',
  'accept-language': '*',
  'sec-fetch-mode': 'cors',
  'user-agent': 'undici',
  'accept-encoding': 'gzip, deflate',
  'content-length': '0'
}
```

So, it's an issue with ohmyfetch's implementation of undici fetching. It doesn't happen with [``unjs/node-fetch-native``](https://github.com/unjs/node-fetch-native) alone.
I also realized it doesn't happen if you omit the body.

**Comment by NozomuIkuta** [comment] 2023-01-11 19:26
Let me close this issue because ohfetch does no longer support undici as of v1.0.0 and there is a workaround for the issue like using other fetch implementation.

**Closed by NozomuIkuta** 2023-01-11 19:26 UTC
Labels: upstream
