### ISSUE TITLE
How can ofetch upload files and obtain real-time progress?

### ISSUE THREAD

**Issue by bbhxwl** [unjs/ofetch#412] opened 2024-07-06 14:25 UTC
### Describe the feature

How can ofetch upload files and obtain real-time progress?

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by chrisspiegl** [comment] 2024-07-06 22:04
Duplicate of https://github.com/unjs/ofetch/issues/45

**Closed** 2024-09-23 09:59 UTC
Labels: enhancement
